export default async function Search(query) {
  var result = [];
  if (!query) {
    const data = await fetch("http://localhost:8000/api/history-details");

    const res = await data.json();
    result = res.info.map((search) => search.history);

    result.reverse();
  } else {
    const companies = [
      "AAPL",
      "MSFT",
      "GOOG",
      "ADSK",
      "AMZN",
      "FB",
      "TSLA",
      "TSM",
      "NVDA",
      "V",
      "JPM",
      "JNJ",
      "BABA",
      "WMT",
      "UNH",
      "BAC",
      "MA",
      "PG",
      "HD",
      "ASML",
      "PYPL",
      "DIS",
      "ADBE",
      "CMCSA",
      "BHP",
      "BMY",
      "C",
      "CHTR",
      "CVX",
      "HDB",
      "HON",
      "INTU",
      "LIN",
      "MCD",
      "MDT",
      "MRNA",
      "MS",
      "PM",
      "QCOM",
      "RY",
      "SAP",
      "SE",
      "SHOP",
      "TMUS",
      "TXN",
      "UPS",
      "NKE",
      "PFE",
      "CRM",
      "LLY",
      "CSCO",
      "ORCL",
      "NFLX",
      "TM",
      "KO",
      "NVO",
      "XOM",
      "DHR",
      "VZ",
      "ABT",
      "INTC",
      "TMO",
      "PEP",
      "ABBV",
      "ACN",
      "NVS",
      "WFC",
      "COST",
      "AVGO",
      "T",
      "MRK",
      "UL",
      "UNP",
      "LOW",
      "BLK",
      "SCHW",
      "GS",
      "SBUX",
      "AXP",
      "AMD",
      "SONY",
      "SNY",
      "BA",
      "RTX",
      "AMT",
      "AMGN",
      "IBM",
      "ISRG",
      "TD",
      "NOW",
      "SQ",
      "TGT",
      "PDD",
      "RIO",
      "EL",
      "AMAT",
      "BUD",
      "JD",
      "SNAP",
    ];
    result = companies.filter((company) => company.startsWith(query));
  }
  return result;
}
