# Generated by Django 3.0 on 2021-08-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.CharField(default='adide', max_length=200),
        ),
    ]
